### ISSUE TITLE
UI for adding events to the schedule.

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/portal#69]
UI for adding events to the schedule. It's a popover that says the action done and also includes other actions to add to calendars. Please use normal bootstrap dialogs and font awesome icons, don't take the screenshot design too seriously

Backend Implementation: #66 

![image](https://user-images.githubusercontent.com/7832610/91508359-ef90ae00-e89c-11ea-8d64-6efe64e10c05.png)
![image](https://user-images.githubusercontent.com/7832610/91508550-6b8af600-e89d-11ea-87a5-a33c0c65690a.png)

- [ ] UI for action
- [ ] Wire up with backend API to add the event to users schedule 
- [ ] Make sure button say the right thing if they already added this event to the schedule

**Comment by samarthdave** [comment]
Procrastination: 1
Samarth: 0
