### ISSUE TITLE
Make this project more like a normal next js app

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/portal#96]
- [x] Make the api "pages" be in the pages folder
- [ ] Integrate with pivot instead of using `join.ts` handler (for the join button AttendedEvents tracking)

**Comment by danabreo** [comment]
api is fine the way it is currently setup, as shown here: [https://nextjs.org/learn/basics/data-fetching/implement-getstaticprops](https://nextjs.org/learn/basics/data-fetching/implement-getstaticprops)
